@extends('layouts.app')
@section('title','Document History')
@section('breadcrumb','Documents / History')
@section('content')
<div class="d-flex align-items-center justify-content-between mb-4">
    <h4 class="fw-bold mb-0">Document History</h4>
</div>
<form method="GET" class="card border-0 shadow-sm mb-3"><div class="card-body py-3">
    <div class="row g-2">
        <div class="col-md-3"><input type="text" name="search" value="{{ request('search') }}" class="form-control form-control-sm" placeholder="Search document #..."></div>
        <div class="col-md-3">
            <select name="document_type" class="form-select form-select-sm">
                <option value="">All Types</option>
                @foreach(\App\Models\DocumentTemplate::DOCUMENT_TYPES as $k=>$v)<option value="{{ $k }}" {{ request('document_type')===$k?'selected':'' }}>{{ $v }}</option>@endforeach
            </select>
        </div>
        <div class="col-md-2"><button class="btn btn-primary btn-sm">Filter</button></div>
    </div>
</div></form>
<div class="card border-0 shadow-sm">
    <div class="card-body p-0">
        <table class="table table-hover align-middle mb-0">
            <thead class="table-light"><tr><th class="ps-4">Doc #</th><th>Type</th><th>Customer</th><th>Vehicle</th><th>Generated By</th><th>Date</th><th class="pe-4"></th></tr></thead>
            <tbody>
                @forelse($documents as $d)
                <tr class="{{ $d->is_voided ? 'table-danger' : '' }}">
                    <td class="ps-4 fw-semibold">{{ $d->document_number }}</td>
                    <td><span class="badge bg-light text-dark">{{ $d->type_label }}</span></td>
                    <td>{{ $d->customer?->full_name ?? '—' }}</td>
                    <td class="small">{{ $d->vehicle ? $d->vehicle->make->name.' '.$d->vehicle->vehicleModel->name : '—' }}</td>
                    <td><small>{{ $d->generatedBy->name }}</small></td>
                    <td><small>{{ $d->generated_at->format('d M Y') }}</small></td>
                    <td class="pe-4">
                        <button type="button" class="btn btn-light btn-sm"
                                onclick="openDocumentViewModal('{{ route('documents.show', $d) }}')">
                            <i class="bi bi-eye"></i>
                        </button>
                    </td>
                </tr>
                @empty
                <tr><td colspan="7" class="text-center py-5 text-muted">No documents generated yet.</td></tr>
                @endforelse
            </tbody>
        </table>
        <div class="px-4 py-3 border-top">{{ $documents->links('pagination::bootstrap-5') }}</div>
    </div>
</div>

{{-- View Modal (iframe preview since documents are full printable pages) --}}
<!-- <div class="modal fade" id="documentViewModal" tabindex="-1">
    <div class="modal-dialog modal-xl modal-dialog-scrollable" style="height: 90vh;">
        <div class="modal-content" style="height: 90vh;">
            <div class="modal-header">
                <h5 class="modal-title">Document Preview</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body p-0">
                <iframe id="documentViewFrame" src="" style="width:100%; height:100%; border:0;"></iframe>
            </div>
        </div>
    </div>
</div> -->


<div class="modal fade" id="documentViewModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-xl modal-dialog-centered">
        <div class="modal-content document-preview-modal">
            <div class="modal-header">
                <h5 class="modal-title">Document Preview</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>

            <div class="modal-body p-0 document-preview-body">
                <iframe
                    id="documentViewFrame"
                    src=""
                    title="Document Preview"
                    class="document-preview-frame">
                </iframe>
            </div>
        </div>
    </div>
</div>
@endsection
