name: Generate Laravel APP Key

on:
  workflow_dispatch:

jobs:
  generate-key:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, intl, gd, zip
          tools: composer
          coverage: none

      - name: Copy .env
        run: cp .env.example .env

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --no-progress --no-scripts

      - name: Generate APP Key
        run: php artisan key:generate

      - name: Show APP Key
        run: grep '^APP_KEY=' .env
